name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.5.x]


    services:
      authorization-server:
        image: eventuateio/customers-and-orders-spring-authorization-server:886f123
        ports:
          - 9000:9000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - name: Install dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm run unit-test

    - name: Fix env to reference authorization server
      run: |
        # 127.0.0.1 or localhost work
        # authorizationserver does not work

        curl --fail -v http://127.0.0.1:9000/actuator/health || echo failed 127.0.0.1:9000
        
        sed 's/localhost:9000/127.0.0.1:9000/g' < template-dotenv-local > .env.local

    - name: Start application
      run: npm run dev &
    
    - name: Wait for application to be ready
      run: npx wait-on@8.0.3 --timeout 10s http://localhost:3000

    - name: Run E2E Tests
      run: npm run e2e-test 